version: "3"

services:

  front-end:
    image: archbungle/front-end:1.0.2
    deploy:
      mode: replicated 
      replicas: 1

  broker-service:
    image: archbungle/broker-service:1.0.3
    deploy:
      mode: replicated
      replicas: 1
  
  listener-service:
    image: archbungle/listener-service:1.0.1
    deploy:
      mode: replicated 
      replicas: 1
  
  authentication-service:
    image: archbungle/authentication-service:1.0.1
    deploy:
      mode: replicated
      replicas: 1
    environment:
      DSN: "host=postgres port=5432 user=postgres password=password dbname=users sslmode=disable timezone=UTC connect_timeout=5"
      
  logger-service:
    image: archbungle/logger-service:1.0.1
    ports:
      - "8082:80"
    deploy:
      mode: replicated
      replicas: 1
  
  mail-service:
    image: archbungle/mail-service:1.0.1
    ports:
      - "8083:80"
    deploy: 
      mode: replicated
      replicas: 1
    environment:
      MAIL_DOMAIN: localhost
      MAIL_HOST: mailhog
      MAIL_PORT: 1025
      MAIL_ENCRYPTION: none
      MAIL_USERNAME: ""
      MAIL_PASSWORD: ""
      FROM_NAME: "John Smith"
      FROM_ADDRESS: traiano@gmail.com
  
  rabbitmq:
    image: 'rabbitmq:3.9-alpine'
    ports: 
      - "5672:5672"
    deploy:
      mode: replicated
      replicas: 1
    volumes:
      - ./db-data/rabbitmq/:/var/lib/rabbitmq/

  mailhog:
    image: 'mailhog/mailhog:latest'
    ports: 
      - "1025:1015"
      - "8025:8025"
    deploy:
      mode: global

  mongo:
    image: 'mongo'
    ports:
      - "27017:27017"
    deploy:
      mode: global
    environment:
      MONGO_INITDB_DATABASE: logs
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./db-data/mongo/:/data/db

  postgres:
    image: 'postgres:14.2'
    ports:
      - "5432:5432"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users
    volumes:
      - /var/lib/postgresql/data

  caddy:
    image: archbungle/micro-caddy:1.0.0
    deploy:
      mode: replicated
      replicas: 1
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
    external: true
  caddy_config:
    external: true
